services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
  express:
    build: .
    ports:
      - "5173:5173"
      - "5174:5174"
      - "8080:8080"
    environment:
      - URL_MONGO=mongodb://mongo
      - DB_MONGO=hangman
    depends_on:
      - mongo
